bratislava/olo.sk

.github/workflows/label.yml
- copied from paas-mpa project
=> ad pr labeler workflow

next/src/app/pages/api/healthcheck.ts
this PR adds healtheck endpoint
=> added missing healthcheck page

next/src/app/api/healthcheck/route.ts, next/src/app/pages/api/healthcheck.ts
- use new App Router syntax and structure https://nextjs.org/docs/app/building-your-application/routing/route-handlers
=> fix healthcheck api endpoint to new app router syntax

next/src/services/graphql/index.ts, next/src/services/graphql/queries/_common.gql, next/src/services/graphql/queries/_header-sections.gql, next/src/services/graphql/queries/pages.gql, strapi/schema.graphql, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/header-sections/branch-map.json, strapi/src/components/header-sections/gallery.json, strapi/src/components/header-sections/image.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
- add page header options to pages in Strapi 
- Image
- Gallery
- Branch Map
- max length of DZ is set to 1, so only 1 header component is allowed
=> Add page header options as dynamic zone components

next/src/pages/articles/[slug].tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/articles.gql, strapi/schema.graphql, strapi/src/api/article/content-types/article/schema.json, strapi/src/api/category/content-types/category/schema.json, strapi/types/generated/contentTypes.d.ts
- add super simple article page
- prepare strapi fields in Article content type
Todos:
- article header and cover image
- whole article layout
- "Pacil sa vam clanok?"
=> #102 Implement basic Article detial page

next/src/_components/common/Button/Button.tsx, next/src/_components/common/Typography/Typography.tsx, next/src/styles/globals.css, next/tailwind.config.ts
- remove globally applied `font-bold` and move it to `Typography`
- cleanup old unused custom classes / we use `Typography` now
=> #33 Fix styles in Typography

.github/workflows/deploy.yml, .github/workflows/validate.yml
- fix typescript validation pipeline by adding `workdir`
- change pipeline to beta version
=> #109 Fix typescript validation pipeline

.github/workflows/deploy.yml, next/.gitignore, next/Dockerfile.storybook, next/kubernetes/base/deployment.yml, next/kubernetes/base/ingress.yml, next/kubernetes/base/kustomization.yml, next/kubernetes/base/service-storybook.yml, next/kubernetes/base/storybook-nginx-conf.yml
* Added new `Dockerfile.storybook` that builds a static storybook website and serves it through NGINX
* Added new GitHub workflow step that builds a storybook image and pushes it to harbor
* Added & change Kubernetes deployment files to server storybook website
- Added custom NGINX config to properly route from `*olo.*.sk/storybook` to application root
=> Add storybook deployment

next/src/components/sections/headers/PageHeaderGallery.tsx
I forgot to push the changes requested by code review in [https://github.com/bratislava/olo.sk/pull/138](https://github.com/bratislava/olo.sk/pull/138)
=> #138 PageHeaderGallery - Make changes according to code review

next/src/components/common/Button/Button.tsx, next/src/components/common/Card/BranchCard.tsx, next/src/components/sections/BranchesSection.stories.tsx, next/src/components/sections/BranchesSection.tsx
- Update branch card design
- Update `Button` component to display links as per the new card design
- Update branch section design to display 3 cards in a row
=> #166 Update branch card and section design

next/src/components/placeholder/BreadcrumbsPlaceholder.tsx, next/src/pages/[...path].tsx, next/src/pages/pages/[slug].tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_common.gql, next/src/services/graphql/queries/articles.gql, next/src/services/graphql/queries/pages.gql, next/src/utils/getFullPath.ts, next/src/utils/getLinkProps.ts, next/src/utils/getPageBreadcrumbs.ts, next/src/utils/getPagePath.ts
The approach is taken from bratislava.sk project.
=> #215 Create proper Pages paths from `parentPage`s

next/src/components/common/Card/ServiceCard.stories.tsx, next/src/components/common/Card/ServiceCard.tsx
- Remove having fixed min width on the card
=> #178 ServiceCard - minor fixes in styling

next/src/services/graphql/api.ts, next/src/services/graphql/queries/menu.gql, strapi/schema.graphql, strapi/src/components/menu/menu-section.json, strapi/types/generated/components.d.ts
- add divider option (mainly for branches and workshops)
- add `specialSectionType` option - planned to be used for latest news
=> #231 Add additional fields to Menu content type

next/src/components/common/Input/Input.tsx, next/src/components/common/Pagination/Pagination.stories.tsx, next/src/components/common/Pagination/PaginationInput.stories.tsx, next/src/components/common/Pagination/PaginationWithInput.tsx, next/src/components/common/Pagination/usePaginationWithInput.ts, next/src/styles/globals.css
- Rename the component -> `PaginationWithInput`
- Refactor implementation -> `usePaginationWithInput`
- Require `aria-label` when `labelText` prop isn't passed
=> #56 Input-based pagination - minor fixes

next/src/components/common/Card/HomepageMainTile.tsx, next/src/components/common/Card/HomepageSmallTile.tsx, next/src/components/layout/Section/SectionHeader.tsx, next/src/components/sections/hompage/ArticlesHomepageSection.tsx, next/src/components/sections/hompage/HeroHomepageSection.tsx, next/src/components/sections/hompage/KoloHomepageSection.tsx, next/src/components/sections/hompage/ServicesHomepageSection.tsx, next/src/pages/index.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/homepage.gql, next/src/utils/useGetLinkProps.ts
- add homepage sections
- closes #200 
- closes #199 
- add showMoreLink to SectionHeader
TODO in further PRs
- Slider in Hero section
- banner card in Kolo section
=> #200 Homepage FE

next/src/components/layout/Section/SectionHeader.tsx, next/src/components/layout/Sections.tsx, next/src/components/sections/FaqSection.stories.tsx, next/src/components/sections/FaqSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, strapi/schema.graphql, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/sections/faq.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
=> #194 Add FaqSection

next/src/services/graphql/api.ts
- fix acciddentally merged PR without regenareted graphql types
=> Fix generated typescript files

next/src/services/graphql/api.ts, strapi/schema.graphql, strapi/src/api/faq-category/content-types/faq-category/schema.json, strapi/types/generated/contentTypes.d.ts
- fix accidentally changed `title` to optional in Faq Categories content type
=> Make title required in Faq Category content type

next/src/pages/[...path].tsx, next/src/pages/articles/[slug].tsx, next/src/pages/documents/[slug].tsx, next/src/pages/faq-categories/[slug].tsx, next/src/pages/index.tsx, next/src/pages/services/[slug].tsx, next/src/pages/workshops/[slug].tsx
=> Temporarily change revalidate to 1 second

next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
=> #358 Make whole links clickable in Menu

.github/workflows/deploy.yml, next/Dockerfile.storybook
* Added Next build envs to storybook deployment action
* Fix Dockerfile.storybook build not failing when build-storybook command fails
=> Fix Storybook deployment

strapi/src/plugins/wysiwyg/admin/src/components/Editor/index.tsx
=> Change richtext editor background to white

next/src/components/sections/hompage/HeroHomepageSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/homepage.gql
Temporarily add one slide, to show how it works and to test it (colour, images, gifs..)
It should work also with gifs 
https://github.com/user-attachments/assets/908eda99-f71f-4183-b9c3-767d0ffb4440
=> #141 Prepare homepage slider

next/src/components/sections/WasteSortingCardsSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, strapi/schema.graphql, strapi/src/components/sections/waste-sorting-cards.json, strapi/types/generated/components.d.ts
=> #382 Add banner to WasteSortingCardsSection

next/src/components/formatting/Markdown.tsx, next/src/pages/_app.tsx, next/src/styles/table.scss
=> #387 Fix table overflow fade

next/src/components/common/Accordion/Accordion.stories.tsx, next/src/components/common/Accordion/Accordion.tsx, next/src/components/common/Accordion/AccordionGroup.stories.tsx, next/src/components/common/Accordion/WasteIcon.tsx, next/src/components/common/Accordion/WasteSortingGuide.stories.tsx, next/src/components/common/Accordion/WasteSortingGuide.tsx, next/src/components/layout/Sections.tsx, next/src/components/sections/SortingGuideAccordionsSection.tsx, next/src/components/sections/SortingGuideSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, strapi/schema.graphql, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/items/sorting-guide-accordion-item.json, strapi/src/components/items/sorting-guide-item.json, strapi/src/components/items/sorting-guide.json, strapi/src/components/sections/sorting-guide-accordions.json, strapi/src/components/sections/sorting-guide.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
- add `SortingGuideSection` and `SortingGuideAccordions` section
TODOs
- accordions have double bottom border when opened
- use some common group parent div to solve all these divider problems
=> #306 Add Sorting guide sections

next/src/components/common/Card/ContactRowCard.tsx, next/src/components/common/ContactBox.tsx, next/src/components/common/OpeningHoursBox.tsx, next/src/components/layout/Sections.tsx, next/src/components/sections/ContactsSection.tsx, next/src/components/sections/OpeningTimesSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, next/src/services/graphql/queries/contacts.gql, next/tailwind.config.ts, strapi/schema.graphql, strapi/src/api/contact/content-types/contact/schema.json, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/sections/contacts.json, strapi/src/components/sections/opening-times.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
TODOs
- https://github.com/orgs/bratislava/projects/33/views/1?pane=issue&itemId=76005014
=> #403 Add Contacts Section and Opening Hours Section

next/src/components/sections/hompage/HeroHomepageSection.tsx, next/tailwind.config.ts
=> #141 Improve homepage slider layout

next/src/components/common/Button/Button.tsx, next/src/components/common/SearchBar/SearchBar.tsx, next/src/components/common/Spinner/Spinner.stories.tsx, next/src/components/common/Spinner/Spinner.tsx
=> Improve Spinner styling

next/src/components/common/Accordion/Accordion.tsx, next/src/components/common/AnchorPill/AnchorPill.tsx, next/src/components/common/Card/BasicCard.tsx, next/src/components/common/Card/BranchCard.stories.tsx, next/src/components/common/Card/BranchCard.tsx, next/src/components/common/Card/MenuItemArticleCard.tsx, next/src/components/common/Card/SearchResultRowCard.tsx, next/src/components/common/Gallery/Gallery.tsx, next/src/components/common/Icon/Icon.stories.tsx, next/src/components/common/Icon/OloIcon.stories.tsx, next/src/components/common/Icon/Pictogram.stories.tsx, next/src/components/formatting/Markdown.tsx, next/src/components/modals/gallery/GallerySlider.tsx, next/src/components/modals/gallery/ImageLightBox.tsx, next/src/components/page-contents/service/ServicePageContent.tsx, next/src/components/sections/DocumentsAllSection.tsx, next/src/components/sections/headers/PageHeaderSideImage.tsx, next/src/components/sections/hompage/KoloHomepageSection.tsx
I also fixed some minor errors and warnings which appeared due to the recent eslint config update
=> #342 Richtext image aspectratio fix

next/src/components/formatting/Markdown.tsx
=> #349 Fix table width

next/src/components/common/OpeningHoursBox.tsx, next/src/components/sections/OpeningTimesSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, strapi/schema.graphql, strapi/src/components/items/opening-times-item.json, strapi/src/components/sections/opening-times.json, strapi/types/generated/components.d.ts
=> #425 Update OpeningTimes section

next/src/components/common/Card/ListingCard.tsx, next/src/components/sections/CardsListSection.tsx, next/src/components/sections/FaqCategoriesSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, strapi/schema.graphql, strapi/src/components/items/cards-list-item.json, strapi/src/components/sections/cards-list.json, strapi/types/generated/components.d.ts
=> #423 listing cards fixes

next/public/locales/sk/translation.json, next/src/components/sections/AliasSection.tsx, next/src/pages/[...path].tsx
Design inspired by Helsinki city website, e.g. https://www.hel.fi/fi/sosiaali-ja-terveyspalvelut/lasten-ja-perheiden-palvelut
=> #347 Implement static generation for Pages along with alias redirect

next/src/components/layout/Sections.tsx, next/src/components/sections/VacanciesSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, strapi/schema.graphql, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/sections/table.json, strapi/src/components/sections/vacancies.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
TODO - get positions from Nalgoo
=> #406 Add Vacancies section placeholder

next/src/components/common/Footer/DesktopFooter.tsx, next/src/components/common/Footer/FooterShared.tsx, next/src/components/common/Footer/MobileFooter.tsx, next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx, next/src/components/common/NavBar/NavMenu/NavMenu.tsx, next/src/pages/[...path].tsx, next/src/pages/_app.tsx, next/src/pages/articles/[slug].tsx, next/src/pages/documents/[slug].tsx, next/src/pages/faq-categories/[slug].tsx, next/src/pages/index.tsx, next/src/pages/services/[slug].tsx, next/src/pages/workshops/[slug].tsx, next/src/utils/prefetchPageSections.ts, next/src/utils/queryOptions.ts
so the changes are visible immediately
=> #422 Fetch menu and footer on client + prefetch

next/src/components/sections/OrderedCardsSection.tsx, next/src/services/graphql/api.ts, strapi/schema.graphql, strapi/src/components/items/ordered-cards-item.json, strapi/types/generated/components.d.ts
- Make `title` (markdown) and `text` fields optional in Strapi
=> #482 Modify ordered cards

next/src/components/sections/ImageAndTextOverlappedSection.stories.tsx, next/src/components/sections/ImageAndTextOverlappedSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, strapi/schema.graphql, strapi/src/components/sections/image-and-text-overlapped.json, strapi/types/generated/components.d.ts
- Replace buttons with `readMoreLink` in Strapi
- Modify FE
=> #489 Replace two buttons with a single link in ImageAndTextOverlappedSection

next/src/components/common/Accordion/AccordionGroup.tsx, next/src/components/common/BranchesMap/BranchesMap.tsx, next/src/components/common/Card/ServicesTile.tsx, next/src/components/common/Sidebar/Divider.tsx, next/src/components/common/Sidebar/SidebarCareer.tsx, next/src/components/common/Sidebar/SidebarContacts.tsx, next/src/components/page-contents/document/DocumentPageContent.tsx, next/src/components/sections/ArticlesSection.tsx, next/src/components/sections/DividerSection.tsx, next/src/components/sections/hompage/KoloHomepageSection.tsx
- Rename `SidebarDivider` to `Divider`
=> #311 Rename SidebarDivider to Divider

next/src/pages/articles/[slug].tsx
- Display `perex` for articles when `perex` is defined
=> #486 Display perex for articles

next/package.json, next/src/components/formatting/Markdown.tsx, next/src/components/formatting/useTransformOloMarkdownLinks.ts, next/src/services/graphql/api.ts, next/src/services/graphql/queries/articles.gql, next/src/services/graphql/queries/documents.gql, next/src/services/graphql/queries/pages.gql, next/src/services/graphql/queries/services.gql, next/src/services/graphql/queries/workshops.gql, next/yarn.lock
This solution is quite cumbersome and requires fetching **everything**.
I take it as a first step in exploring possible solutions.
The main obstacle is that we need to use the hook useGetFullPath to acces the correct link path.
=> #255 Richtext - links for OLO content types

next/src/components/common/Box/BranchMap.tsx, next/src/components/common/Card/BranchCard.tsx, next/src/components/sections/headers/PageHeaderGallery.tsx, next/src/utils/useGetLinkProps.ts
=> Minor fixes

strapi/package.json, strapi/types/generated/components.d.ts
=> #407 Fix deploy after adding new plugin

strapi/package.json, strapi/yarn.lock
=> #407 Install xlsx redundantelly also in strapi folder

next/public/locales/sk/translation.json, next/src/components/common/Card/BasicRowCard.tsx, next/src/components/common/Sidebar/SidebarContacts.tsx, next/src/components/layout/PageHeaderSections.tsx, next/src/components/layout/Sidebars.tsx, next/src/components/page-contents/service/ServicePageContent.tsx, next/src/components/sections/AliasInfoMessage.tsx, next/src/components/sidebars/ContactsSidebar.tsx, next/src/pages/[...path].tsx, next/src/pages/services/[slug].tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sidebars.gql, next/src/services/graphql/queries/branches.gql, next/src/services/graphql/queries/pages.gql, strapi/schema.graphql, strapi/src/api/branch/content-types/branch/schema.json, strapi/src/api/page/content-types/page/schema.json, strapi/src/components/sidebars/contacts-sidebar.json, strapi/src/components/sidebars/empty-sidebar.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
- add new  `sidebar` dynamic zone to Pages
- create FE components and implement basic layout for sidebar
Note that layout needs revisit, because this was just quickfix.
=> #295 Add sidebar dynamic zone to Pages

next/public/locales/sk/translation.json, next/src/components/common/Card/BasicRowCard.tsx, next/src/components/common/SeoHead.tsx, next/src/components/common/Sidebar/SidebarContacts.tsx, next/src/components/layout/PageHeaderSections.tsx, next/src/components/layout/Sidebars.tsx, next/src/components/page-contents/service/ServicePageContent.tsx, next/src/components/sections/AliasInfoMessage.tsx, next/src/components/sidebars/ContactsSidebar.tsx, next/src/pages/[...path].tsx, next/src/pages/services/[slug].tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sidebars.gql, next/src/services/graphql/queries/branches.gql, next/src/services/graphql/queries/pages.gql, next/src/services/graphql/queries/seo.gql, next/src/services/graphql/queries/services.gql, strapi/.strapi/client/app.js, strapi/package.json, strapi/schema.graphql, strapi/src/api/branch/content-types/branch/schema.json, strapi/src/api/page/content-types/page/schema.json, strapi/src/api/service/content-types/service/schema.json, strapi/src/components/shared/meta-social.json, strapi/src/components/shared/seo.json, strapi/src/components/sidebars/contacts-sidebar.json, strapi/src/components/sidebars/empty-sidebar.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts, strapi/yarn.lock
Note: This is the first time we use official `@strapi/plugin-seo` so testing is needed if it fits our needs.
For now, we keep it simple and use only basic meta attributes.
=> #540 Install and use `@strapi/plugin-seo`

next/src/components/common/Card/BasicCard.tsx, next/src/components/layout/Sections.tsx, next/src/components/sections/WasteRemovalCardsSection.stories.tsx, next/src/components/sections/WasteRemovalCardsSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, next/src/services/graphql/queries/services.gql, strapi/schema.graphql, strapi/src/api/service/content-types/service/schema.json, strapi/src/components/sections/waste-removal-cards-section.json, strapi/src/components/sections/waste-removal-cards.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
- Create a new section for waste removal cards
- The section can be added as a dynamic zone within _Services_ only
=> #384 Section - waste removal cards

strapi/config/sync/core-store.plugin_content_manager_configuration_components##items.opening-hours-item.json, strapi/config/sync/core-store.plugin_content_manager_configuration_components##items.slide.json, strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.richtext.json, strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.waste-collection-days.json, strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.waste-removal-cards.json, strapi/config/sync/core-store.plugin_content_manager_configuration_components##shared.seo.json, strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##branch.branch.json, strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##opening-time.opening-time.json, strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json, strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##service.service.json
I copied db from prod to local, exported config, reverted some files that were already in repo but not in prod db (faq, pickup-day, iframe-section, waste-collection-days).
=> Reexport config-sync

next/src/components/common/FormCtaBanner/FormCtaBanner.tsx, next/src/components/sections/FormCtaBannerSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, strapi/schema.graphql, strapi/src/components/sections/form-cta-banner.json, strapi/types/generated/components.d.ts
=> Refactor FormCtaBanner

next/src/components/formatting/Markdown.module.scss, next/src/components/formatting/Markdown.tsx, next/src/components/sections/RichtextSection.tsx
- closes #677
- closes #684
- closes #683
=> Quickfix spacings and alignments in Richtext

next/src/components/common/Slider/Slider.stories.tsx, next/src/components/common/Slider/Slider.tsx, strapi/types/generated/components.d.ts
- Use `top` positioning instead of `bottom` to prevent the slider image from falling down when the slide animates
https://github.com/user-attachments/assets/131d5b82-e850-4bc2-b79a-b3cd0d5dcb2a
=> #669 Prevent slider image from falling down on animating

strapi/src/plugins/wysiwyg/admin/src/components/Wysiwyg/index.tsx
=> Add richtext field description into the wysiwyg plugin

next/src/components/layout/Sections.tsx, next/src/pages/[...path].tsx, strapi/types/generated/components.d.ts
=> #607 Fix sidebar display bug

next/src/components/common/Card/MenuItemWorkshopCard.tsx, next/src/components/common/Card/WorkshopCard.tsx, next/src/components/common/Icon/Icon.tsx, next/src/components/common/Icon/OloIcon.tsx, next/src/components/common/NavBar/NavMenu/NavMenuSingleColumnList.tsx, next/src/components/sections/WorkshopsSection.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/workshops.gql, strapi/config/sync/admin-role.strapi-super-admin.json, strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##workshop.workshop.json, strapi/schema.graphql, strapi/src/api/workshop/content-types/workshop/schema.json, strapi/types/generated/components.d.ts, strapi/types/generated/contentTypes.d.ts
=> #705 add `iconName` field to Workshops

next/src/components/common/NavBar/MobileNavBarHeader/MobileNavBarHeader.tsx, next/tailwind.config.ts
- Remove the black border which appears at the bottom of the header
=> #531 Fix mobile header display

next/src/components/layout/Section/SectionHeader.tsx, next/src/components/sections/WasteCollectionDays.tsx, next/src/services/graphql/api.ts, next/src/services/graphql/queries/_page-sections.gql, next/src/services/meili/fetchers/wasteCollectionDaysFetcher.ts, strapi/schema.graphql, strapi/src/components/sections/waste-collection-days.json, strapi/types/generated/components.d.ts
- set proper gaps in section
- set min height for table cells
- change pagesize to 10
- add proper translation for no results
- add validityMessage and richtext format for text - not ideal, but needed for this case
- figma wip design: https://www.figma.com/design/2qF09hDT9QNcpdztVMNAY4/OLO-Web?node-id=9011-20534&node-type=frame&m=dev
Prod: http://localhost:3000/odpad/zistite-si-svoj-odvozovy-den?scrollId=kuchynsky-biologicky-rozlozitelny-odpad-kbro
Validity message and richtext formatting:
Longer validity message:
=> #632 WasteCollectionDays section styling and finishing touches

next/package.json, next/tailwind.config.ts, next/yarn.lock
- Install `tailwindcss-animate`
- Write code implementing custom animations
=> Set-up tailwindcss-animate

next/src/components/common/Card/LocationCard.tsx
=> #733 Fix justifying content in LocationCard

next/src/components/common/Card/MenuItemArticleCard.tsx, next/src/components/common/Card/MenuItemBranchCard.tsx, next/src/components/common/Card/MenuItemWorkshopCard.tsx, next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
- Unwrap cards from Radix link
- NOTE: This also fixes focus ring behaviour for menu cards
=> #558 Refactor menu cards

next/src/components/common/Card/CareerRowCard.tsx, next/src/pages/career/[id].tsx
Fix paddings in Nalgoo Career detail position
=> #405 - Fix paddings in Career position detail page

next/src/components/sections/GlobalSearchSection.tsx
isError, isLoading and isPending are taken care of in SearchResults
=> Remove unneeded comments
